-- noormagazine_schema.sql
SET FOREIGN_KEY_CHECKS=0;
CREATE DATABASE IF NOT EXISTS `noormagazine` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `noormagazine`;
DROP TABLE IF EXISTS `favorites`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `magazines`;
DROP TABLE IF EXISTS `articles`;
DROP TABLE IF EXISTS `settings`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id INT PRIMARY KEY DEFAULT 1,
  site_name VARCHAR(255) DEFAULT 'مجله فرهنگی نور',
  tagline VARCHAR(255) DEFAULT '',
  logo_url TEXT,
  phone VARCHAR(50),
  email VARCHAR(150),
  social_json TEXT,
  footer_text TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS articles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255),
  author VARCHAR(150),
  author_photo TEXT,
  category VARCHAR(50),
  tags_json TEXT,
  content MEDIUMTEXT,
  excerpt TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS magazines (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255),
  month INT,
  year INT,
  description TEXT,
  cover_image TEXT,
  pdf_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  article_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
